/* ==========================================================
   DORF-HANDELSMANAGER — PRODUCTS.JS
   Startprodukte für jeden Händler
   ========================================================== */

export const products = [
  /* ===========================
     BALDUR — SCHMIEDEWAREN
     =========================== */
  {
    id: "W-001",
    name: "Eisenlangschwert",
    type: "Waffe",
    vendorId: "baldur",
    rarity: "Common",
    buyPrice: { B: 0, S: 8, G: 0, P: 0 },
    sellPrice: { B: 0, S: 3, G: 0, P: 0 },
    stock: 6,
    minFame: 0,
    desc: "Ein robustes Langschwert, geschmiedet für einfache Milizsoldaten.",
    effect: "+1 Schaden",
  },
  {
    id: "W-002",
    name: "Kettenhemd (leicht)",
    type: "Rüstung",
    vendorId: "baldur",
    rarity: "Common",
    buyPrice: { B: 0, S: 10, G: 0, P: 0 },
    sellPrice: { B: 0, S: 4, G: 0, P: 0 },
    stock: 4,
    minFame: 0,
    desc: "Flexibles Hemd aus miteinander verbundenen Eisenringen.",
    effect: "+1 Verteidigung",
  },
  {
    id: "W-003",
    name: "Runenstahl-Schwert",
    type: "Waffe",
    vendorId: "baldur",
    rarity: "Rare",
    buyPrice: { B: 0, S: 0, G: 2, P: 0 },
    sellPrice: { B: 0, S: 0, G: 1, P: 0 },
    stock: 2,
    minFame: 1,
    desc: "Ein Schwert, das mit alten Runen verstärkt wurde.",
    effect: "+2 Schaden, +1 Verteidigung",
  },
  {
    id: "W-004",
    name: "Feuerstahl-Hammer",
    type: "Waffe",
    vendorId: "baldur",
    rarity: "Legendary",
    buyPrice: { B: 0, S: 0, G: 0, P: 1 },
    sellPrice: { B: 0, S: 0, G: 30, P: 0 },
    stock: 1,
    minFame: 2,
    desc: "Ein legendärer Hammer, der bei jedem Schlag Funken sprüht.",
    effect: "+4 Feuerschaden",
  },

  /* ===========================
     MADLEN — MAGISCHER SHOP
     =========================== */
  {
    id: "M-001",
    name: "Heilrolle (klein)",
    type: "Rolle",
    vendorId: "madlen",
    rarity: "Common",
    buyPrice: { B: 0, S: 12, G: 0, P: 0 },
    sellPrice: { B: 0, S: 4, G: 0, P: 0 },
    stock: 10,
    minFame: 0,
    desc: "Ein kleiner Zauber, der Wunden heilt.",
    effect: "Heilt 1W4 Lebenspunkte",
  },
  {
    id: "M-002",
    name: "Runenstaub",
    type: "Komponente",
    vendorId: "madlen",
    rarity: "Common",
    buyPrice: { B: 0, S: 8, G: 0, P: 0 },
    sellPrice: { B: 0, S: 2, G: 0, P: 0 },
    stock: 8,
    minFame: 0,
    desc: "Magischer Staub, der für Runenrituale benötigt wird.",
    effect: "Zutat für Runenmagie",
  },
  {
    id: "M-003",
    name: "Schutzamulett der Ruhe",
    type: "Amulett",
    vendorId: "madlen",
    rarity: "Rare",
    buyPrice: { B: 0, S: 0, G: 1, P: 0 },
    sellPrice: { B: 0, S: 0, G: 0, P: 0 },
    stock: 2,
    minFame: 1,
    desc: "Hält böse Energien fern.",
    effect: "+2 Verteidigung gegen Magie",
  },

  /* ===========================
     ELDA & NICO VOSS — ALCHEMIE
     =========================== */
  {
    id: "A-001",
    name: "Heiltrank (klein)",
    type: "Trank",
    vendorId: "voss",
    rarity: "Common",
    buyPrice: { B: 0, S: 6, G: 0, P: 0 },
    sellPrice: { B: 0, S: 2, G: 0, P: 0 },
    stock: 15,
    minFame: 0,
    desc: "Stellt eine kleine Menge Lebenspunkte wieder her.",
    effect: "Heilt 1W6 HP",
  },
  {
    id: "A-002",
    name: "Antidot",
    type: "Trank",
    vendorId: "voss",
    rarity: "Common",
    buyPrice: { B: 0, S: 10, G: 0, P: 0 },
    sellPrice: { B: 0, S: 3, G: 0, P: 0 },
    stock: 8,
    minFame: 0,
    desc: "Gegen Gifte aller Art.",
    effect: "Neutralisiert Giftzustände",
  },
  {
    id: "A-003",
    name: "Elixier des Lebens",
    type: "Trank",
    vendorId: "voss",
    rarity: "Rare",
    buyPrice: { B: 0, S: 0, G: 1, P: 0 },
    sellPrice: { B: 0, S: 0, G: 0, P: 0 },
    stock: 2,
    minFame: 2,
    desc: "Ein seltener Trank, der Wunden und Müdigkeit heilt.",
    effect: "Heilt vollständig",
  },

  /* ===========================
     TRAVELLER — EXOTISCHE WAREN
     =========================== */
  {
    id: "T-001",
    name: "Seide aus Osten",
    type: "Handelsware",
    vendorId: "trav",
    rarity: "Rare",
    buyPrice: { B: 0, S: 0, G: 1, P: 0 },
    sellPrice: { B: 0, S: 0, G: 0, P: 0 },
    stock: 1,
    minFame: 1,
    desc: "Hochwertige Stoffe aus entfernten Regionen.",
    effect: "Wertvoll für Handel",
  },
  {
    id: "T-002",
    name: "Gewürzmischung",
    type: "Handelsware",
    vendorId: "trav",
    rarity: "Common",
    buyPrice: { B: 0, S: 5, G: 0, P: 0 },
    sellPrice: { B: 0, S: 1, G: 0, P: 0 },
    stock: 5,
    minFame: 0,
    desc: "Exotisches Gewürz für feine Speisen.",
    effect: "Steigert Stimmung",
  },

  /* ===========================
     OBSTHÄNDLER
     =========================== */
  {
    id: "O-001",
    name: "Äpfel (Korb)",
    type: "Lebensmittel",
    vendorId: "obst",
    rarity: "Common",
    buyPrice: { B: 20, S: 1, G: 0, P: 0 },
    sellPrice: { B: 5, S: 0, G: 0, P: 0 },
    stock: 20,
    minFame: 0,
    desc: "Frische Äpfel aus der Region.",
    effect: "Sättigt leicht",
  },
  {
    id: "O-002",
    name: "Getrocknete Pflaumen",
    type: "Lebensmittel",
    vendorId: "obst",
    rarity: "Common",
    buyPrice: { B: 0, S: 1, G: 0, P: 0 },
    sellPrice: { B: 0, S: 0, G: 0, P: 0 },
    stock: 30,
    minFame: 0,
    desc: "Gut haltbare Wegzehrung.",
    effect: "Energie +1",
  },

  /* ===========================
     TAVERNE — ZUR MÜDEN MONDSICHEL
     =========================== */
  {
    id: "TV-001",
    name: "Hausbier (Krug)",
    type: "Getränk",
    vendorId: "tav",
    rarity: "Common",
    buyPrice: { B: 0, S: 2, G: 0, P: 0 },
    sellPrice: { B: 0, S: 1, G: 0, P: 0 },
    stock: 30,
    minFame: 0,
    desc: "Lokales, kräftiges Bier.",
    effect: "Stimmung +1",
  },
  {
    id: "TV-002",
    name: "Eintopf des Tages",
    type: "Essen",
    vendorId: "tav",
    rarity: "Common",
    buyPrice: { B: 0, S: 5, G: 0, P: 0 },
    sellPrice: { B: 0, S: 2, G: 0, P: 0 },
    stock: 15,
    minFame: 0,
    desc: "Warmes, sättigendes Gericht.",
    effect: "Erholung +2",
  },
  {
    id: "TV-003",
    name: "Zimmer (eine Nacht)",
    type: "Dienstleistung",
    vendorId: "tav",
    rarity: "Common",
    buyPrice: { B: 0, S: 10, G: 0, P: 0 },
    sellPrice: { B: 0, S: 5, G: 0, P: 0 },
    stock: 5,
    minFame: 0,
    desc: "Ein einfaches Bett, um sich zu erholen.",
    effect: "Erholt komplett über Nacht",
  },
];
